services:

  data:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports: 
        - "1433:1433"
    env_file:
      - ./Common.env
    environment:
      - ACCEPT_EULA=Y
    volumes: 
        - sqldata:/var/opt/mssql 
    networks: 
        - ecommerce_net

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    env_file:
      - ./Common.env
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmqUser
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ecommerce_net
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ./Common.env
    environment:
      REDIS_INSTANCENAME: "CatalogService:"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce_net

  api-gateway:
    container_name: api-gateway
    build:
      context: ./ECommercePlatform
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - identity
      - catalog
      - inventory
      - order
      - payment
    networks:
      - ecommerce_net

  identity:
    container_name: identity
    build:
      context: ./ECommercePlatform
      dockerfile: IdentityService/Dockerfile
    ports:
      - "5001:8080"
    env_file:
      - ./Common.env
    environment:
      - ConnectionStrings__IdentityDb=Server=sqlserver;Database=IdentityDb;User Id=sa;Password=yourStrongPassword12!@;TrustServerCertificate=True
    restart: on-failure
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    depends_on:
      - data
    networks:
      - ecommerce_net
    
  catalog:
    container_name: catalog
    build:
      context: ./ECommercePlatform
      dockerfile: CatalogService/Dockerfile
    ports:
      - "5002:8080"
    env_file:
      - ./Common.env
    environment:
      - ConnectionStrings__CatalogDb=Server=sqlserver;Database=CatalogDb;User Id=sa;Password=yourStrongPassword12!@;TrustServerCertificate=True
    restart: on-failure
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    depends_on:
      - data
      - rabbitmq
      - redis
    networks:
      - ecommerce_net

  inventory:
    container_name: inventory
    build:
      context: ./ECommercePlatform
      dockerfile: InventoryService/Dockerfile
    ports:
      - "5003:8080"
    env_file:
      - ./Common.env
    environment:
      - ConnectionStrings__InventoryDb=Server=sqlserver;Database=InventoryDb;User Id=sa;Password=yourStrongPassword12!@;TrustServerCertificate=True
    restart: on-failure
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    depends_on:
      - data
      - rabbitmq
    networks:
      - ecommerce_net

  order:
    container_name: order
    build:
      context: ./ECommercePlatform
      dockerfile: OrderService/Dockerfile
    ports:
      - "5004:8080"
    env_file:
      - ./Common.env
    environment:
      - ConnectionStrings__OrdersDb=Server=sqlserver;Database=OrdersDb;User Id=sa;Password=yourStrongPassword12!@;TrustServerCertificate=True
    restart: on-failure
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    depends_on:
      - data
      - rabbitmq
    networks:
      - ecommerce_net

  payment:
    container_name: payment
    build:
      context: ./ECommercePlatform
      dockerfile: PaymentService/Dockerfile
    ports:
      - "5005:8080"
    env_file:
      - ./Common.env
    environment:
      - ConnectionStrings__PaymentDb=Server=sqlserver;Database=PaymentDb;User Id=sa;Password=yourStrongPassword12!@;TrustServerCertificate=True
    restart: on-failure
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    depends_on:
      - data
      - rabbitmq
    networks:
      - ecommerce_net

networks:
  ecommerce_net:

volumes:
  rabbitmq_data:
  data-protection:
  sqldata:
  redis_data: